### PR TITLE
Quad tree integration test

### PR DESCRIPTION
**Pull request by piotr-j**
Added integration test to core and fixed stupid but in tree itself

### CODE REVIEW

**Comment by piotr-j** [comment]
Figured a simple usage example would be useful. At any rate, the bugfix is quite useful.

**Comment by DaanVanYperen** [comment]
Lets move the example to wiki, can you make a pr with just the bugfix?

**Comment by piotr-j** [comment]
Its 3 lines, faster if you will do it manually. You can probably merge just one commit somehow as well.

**Comment by DaanVanYperen** [comment]
good point! Thanks for the fix. :cookie:

**Comment by DaanVanYperen** [comment]
Leaving this open for now till decide what to do with the test.

**Comment by DaanVanYperen** [comment]
@piotr-j have you found any good applications for it yet in ECS land? I tried using it for https://github.com/DaanVanYperen/odb-benchmarks-are-useless but so far i'm making things worse ;)

**Comment by DaanVanYperen** [comment]
Tests can't hurt.

**Comment by piotr-j** [comment]
Oh, hai. Well not really ecs specific, but I do use one for collapsing a bunch of box2d bodies into larger ones on a grid. http://i.imgur.com/okgUt0h.png
QT is mainly useful for finding if things can overlap or whats under touch point when there are a lot of entities. Been trying to use it in a shmup, but I cant really make it faster then box2d in c++

**Pull request merged**
