### PR TITLE
added new module with profiler for systems

### PR DESCRIPTION
**Pull request by piotr-j**
See #72. Usage example would be nice, but even simple thing is feels heavy to include in tests or wiki and it requires a bunch of dependancies. See a working trivial example [here](https://github.com/piotr-j/libgdxplayground/tree/master/core/src/io/piotrjastrzebski/playground/ecs/profilerv2). There are no tests just yet, want some feedback first on the apis.

### CODE REVIEW

**Comment by DaanVanYperen** [comment]
Looks fine overall. Detailing would be:
- [ ] Small error in gwt.xml (see above).
- [ ] `Plugin`. I can whip that up, since we'll probably need some small API tweaks elsewhere.
- [ ] Tests. Lets keep it simple, single wold+plugin integration test should suffice.

Let me know when you are ready to merge!

**Comment by piotr-j** [comment]
Fixed gwt thing, I didnt test it on gwt but I see no reason why it wouldn't work, nothing fancy in here. 
For integration test, something like I linked at the top would be sufficient? Maybe compressed even more. 
Ill look into the `Plugin` stuff

**Comment by DaanVanYperen** [comment]
> Dunno about plugin, from what I understand a system is required

Goal with plugin is to set up an extension to odb. Systems are not required, though it's a bit weird if we don't ECS this baby up! Skip the plugin for now.

**Comment by DaanVanYperen** [comment]
I don't mind forcing some choices on the user, this is mainly a convenience feature instead of something that needs to match game, so closer to zero config the better! Anyone who wants to tie it in perfectly can just circumvent the plugin.

**Comment by DaanVanYperen** [comment]
argghhh these were pointed at master! @_@

**Comment by piotr-j** [comment]
welp, I expected a bit of dev before merge

**Comment by DaanVanYperen** [comment]
I'll hands-off so you can submit your changes. next PR to dev branch please! :)

**Pull request merged**
