### PR TITLE
Event polling and pooling

### PR DESCRIPTION
**Pull request by Namek**
2nd iteration -> #53
This PR contains #54

### CODE REVIEW

**Comment by DaanVanYperen** [comment]
ohhh nice! Let me take a quick gander.

**Comment by DaanVanYperen** [comment]
Looks great! I like the change to system, will make it more flexible. Didn't think of making a custom pool to get rid of the libgdx dependency and interface requirement. nice!

--

Would you mind changing the following? Right now the PR spreads the strategy over both the system and the strategy, and assumes all users want to pool or dispatch on process.

1. If we change the Strategy interface so it gets a process() method, chain it from the system, and move all the polling implementation into a PollingPooledEventStrategy, we make no more assumptions. The system is just a dumb proxy container.

`<T extends Event> T dispatch( Class<T> eventClass )` is a good idea. It fits with the patterns we're used to in Artemis to begin with. 

2. For now keep it and add it to the strategy interface as well, and re-add void dispatch( Event event ) with `@deprecated` for backwards compatibility, Just throw NotImplementedExceptions for strategies that don't support one or the other.

3. Last one, Having Pooling static will make the strategy unusable in multi threaded setups (think client/server in same vm). Probably best to just instance it. 

I know some of these feel like it's not the neatest but we'll iterate towards a clean design with time. 

Have you done any benchmarking? I'm interested to know how this dispatcher performs.

**Comment by DaanVanYperen** [comment]
One last addition. Probably want to document the particulars of the pooling on the strategy (specifically that the user is responsible for a reset before use, and that we don't clear the event upon pooling so any object references on it might be a hostage from the GC).

**Comment by DaanVanYperen** [comment]
oh, uh. https://github.com/DaanVanYperen/artemis-odb-contrib/pull/35
I already made benchmarking? XD Good thing I remember everything I do. yep. After the PR I'll hook it up to this.

**Comment by Namek** [comment]
I'll take a look at your notes later but I have one quick question for now - is at least #54 ok? If yes, then I'll continue work on top of that single commit.

**Comment by DaanVanYperen** [comment]
Hey Namek! The comments apply to both.  It's just some detailing requests, the functionality and EventSystem contract stays the same.

Sorry for the long text. I think it's probably more time intensive to read than to implement ;)

**Comment by Namek** [comment]
I was afraid that you will be wanting exactly those changes. But now I'm sure :D

**Comment by Namek** [comment]
I've got something ready to PR:ed. Let's quickly discuss one thing - do you agree to change `EventManager` into `EventSystem` **now**? Or wanna having both classes?

**Pull request closed without merging**
