### PR TITLE
Events: polling and pooling

### PR DESCRIPTION
**Pull request by Namek**
Events: morph EventManager into EventSystem.
Add new polling + pooling dispatching strategy.
Add pooling utils.

Refers to #55, #53. Fixes #56 

Commit rebased to `develop` branch.

### CODE REVIEW

**Comment by DaanVanYperen** [comment]
AHHHHHHHHHHH stop opening new pull requests! XD

**Comment by DaanVanYperen** [comment]
What did you change specifically : p

**Comment by DaanVanYperen** [comment]
I'm done merging, was just getting a  sane benchmark going.

**Comment by Namek** [comment]
1. In comments there was `PoolCollection` instead of `PoolsCollection`
2. rebased to `develop` branch

**Pull request closed without merging**
