### PR TITLE
Add PollingEventDispatcher.

### PR DESCRIPTION
**Pull request by Namek**

### CODE REVIEW

**Comment by Namek** [comment]
refers to #53

**Comment by DaanVanYperen** [comment]
We'll probably eventually refactor the existing systems toward that. Perhaps separate queuing from dispatching. makes most sense to revisit if/when https://github.com/junkdog/artemis-odb/issues/221 gets finished.

**Comment by DaanVanYperen** [comment]
Pfff I didn't even notice this was a pull request last night, sorry about that!

Looks good. The only thing missing is tests. No need to write all the tests yourself, you can just extend a pre existing testing class ->

See https://github.com/DaanVanYperen/artemis-odb-contrib/blob/develop/contrib-eventbus/src/test/java/net/mostlyoriginal/api/event/dispatcher/PollingPooledEventDispatcherTest.java for an example.

`mvn test` in project root will run it. Should show up as 'Running <testclassname>' in output.

**Comment by Namek** [comment]
?

**Comment by DaanVanYperen** [comment]
Thanks Namek!

**Pull request merged**
